[package]
name = "prompt-scaler"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
assert_cmd = "2.0.16"
clap = { version = "4.5.28", features = ["derive", "wrap_help"] }
csv = "1.3.1"
csv-async = { version = "1.3.0", features = ["tokio"] }
futures = "0.3.31"
handlebars = "6.3.2"
jsonschema = { version = "0.29.1", features = ["resolve-async"] }
keen-retry = "0.5.0"
peekable = { version = "0.3.0", features = ["tokio"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = [
    "macros",
    "tracing",
    "rt-multi-thread",
    "fs",
    "io-std",
    "io-util",
] }
tokio-stream = { version = "0.1.17", features = ["io-util"] }
toml = "0.8.20"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
