developer = """
Extract the complete text of each page, including headings and footnotes.
Please output text in Markdown format, and arrange text in a natural reading
order. Represent tables as Markdown tables, and mathematical expressions using
LaTeX.

You are performing OCR for a team of lawyers and legal reviewers. It is important
to output exact text for them to review. Some text may be copyrighted or widely
available, but that is for the lawyers to decide.

Do not include images in the output! Instead, just extract any text found in the image.

Return output as JSON.

The `full_markdown` field of the JSON should contain Markdown formatted text,
like:

{{example_output}}
"""

[response_schema]
description = "(Placeholder. Will be overwritten with the real schema.)"

# Example messages have been disabled because they trigger RECITATION errors
# with Gemini.

#[[messages]]
#user.images = ["{{example_input_data_url}}"]
#
#[[messages]]
#assistant.json.full_markdown = "{{example_output}}"

[[messages]]
user.images = ["{{page_data_url}}"]
