# generated by datamodel-codegen:
#   filename:  tmp_schema.json
#   timestamp: 2025-04-24T11:41:06+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class ChatInput(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: Annotated[Any, Field(description='The unique ID of the work item.')]
