# generated by datamodel-codegen:
#   filename:  tmp_schema.json
#   timestamp: 2025-04-20T14:18:51+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class ChatInput(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: Annotated[Any, Field(description="The record's unique identifier.")]
