# generated by datamodel-codegen:
#   filename:  tmp_schema.json
#   timestamp: 2025-05-03T19:36:09+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class User(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    images: Annotated[
        Optional[List[str]],
        Field(description='Images to include with the user message, provided as URLs.'),
    ] = []
    text: Annotated[Optional[str], Field(description='Text provided by the user.')] = (
        None
    )


class Message1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user: User


class Assistant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    json_: Annotated[
        Any,
        Field(
            alias='json',
            description='The assistant response. This is always a JSON [`Value`].',
        ),
    ]


class Message2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    assistant: Assistant


class Message(RootModel[Union[Message1, Message2]]):
    root: Annotated[
        Union[Message1, Message2],
        Field(
            description='A message, and optionally a response (represented as a JSON object).\n\nWe would also have a `State: PromptState` field here, but that interacts badly with the [`Deserialize`] trait from [`serde`]. So just pretend that this type exists in two versions: one [`Template`] and one [`Rendered`].'
        ),
    ]


class ScalarType1(str, Enum):
    string = 'string'


class ScalarType2(str, Enum):
    number = 'number'


class ScalarType3(str, Enum):
    boolean = 'boolean'


class ScalarType(RootModel[Union[ScalarType1, ScalarType2, ScalarType3]]):
    root: Annotated[
        Union[ScalarType1, ScalarType2, ScalarType3],
        Field(description='Basic types we support.'),
    ]


class Schema1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: Annotated[str, Field(description='The path to the schema.')]


class Schema2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    json_: Annotated[
        Any, Field(alias='json', description='The schema as a JSON Value.')
    ]


class SimpleSchema3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Annotated[str, Field(description='A description of this value.')]
    enum: Annotated[Optional[List], Field(description='Allowed enum values.')] = None
    type: Annotated[
        Optional[ScalarType], Field(description='The type of this scalar.')
    ] = None


class ChatPrompt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    developer: Annotated[
        Optional[str],
        Field(description='The developer (aka "system") message, if any.'),
    ] = None
    messages: Annotated[List[Message], Field(description='Messages.')]
    response_schema: Annotated[Schema, Field(description='Our schema.')]


class Schema(RootModel[Union[Schema1, Schema2, SimpleSchema]]):
    root: Annotated[
        Union[Schema1, Schema2, SimpleSchema],
        Field(description='Either an external or an internal schema.'),
    ]


class SimpleSchema1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Annotated[str, Field(description='A description of this value.')]
    items: Annotated[SimpleSchema, Field(description='The items in the array.')]


class SimpleSchema2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: Annotated[str, Field(description='A description of this value.')]
    properties: Annotated[
        Dict[str, SimpleSchema], Field(description='The properties of the object.')
    ]
    title: Annotated[Optional[str], Field(description='The title of this object.')] = (
        None
    )


class SimpleSchema(RootModel[Union[SimpleSchema1, SimpleSchema2, SimpleSchema3]]):
    root: Annotated[
        Union[SimpleSchema1, SimpleSchema2, SimpleSchema3],
        Field(description='A simplified version of JSON Schema, used for validation.'),
    ]


ChatPrompt.model_rebuild()
Schema.model_rebuild()
SimpleSchema1.model_rebuild()
SimpleSchema2.model_rebuild()
