# generated by datamodel-codegen:
#   filename:  ChatInput.json
#   timestamp: 2025-08-25T16:54:51+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class ChatInput(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: Annotated[Any, Field(description='The unique ID of the work item.')]
