# generated by datamodel-codegen:
#   filename:  tmp_schema.json
#   timestamp: 2025-05-03T19:36:10+00:00

from __future__ import annotations

from typing import Annotated, Any, Optional

from pydantic import BaseModel, Field


class OcrInput(BaseModel):
    id: Annotated[Any, Field(description='The unique ID of the work item.')]
    password: Annotated[
        Optional[str],
        Field(description='The password to decrypt the PDF file, if any.'),
    ] = None
    path: Annotated[str, Field(description='The path to the PDF file.')]
